services:
  db:
    image: pgvector/pgvector:pg18
    restart: always
    ports:
      - "5432:5432"
    environment:
      DATABASE_URL: postgres://${{PGUSER}}:${{PGPASSWORD}}@${{PGHOST}}:${{PGPORT}}/${{PGDATABASE}}
      DATABASE_URL_PRIVATE: postgres://${{PGUSER}}:${{PGPASSWORD}}@${{PGHOST_PRIVATE}}:${{PGPORT_PRIVATE}}/${{PGDATABASE}}
      PGDATA: "/var/lib/postgresql/db_data"
      PGDATABASE: "${{POSTGRES_DB}}"
      PGHOST: "${{RAILWAY_TCP_PROXY_DOMAIN}}"
      PGHOST_PRIVATE: "${{RAILWAY_PRIVATE_DOMAIN}}"
      PGPASSWORD: "${{POSTGRES_PASSWORD}}"
      PGPORT: "5432"
      PGPORT_PRIVATE: "5432"
      PGUSER: "${{POSTGRES_USER}}"
      POSTGRES_DB: "railway"
      POSTGRES_PASSWORD: "lp8KIbZ~M7uPCrfoLa3s8iFj72npQB2E"
      POSTGRES_USER: "postgres"
    volumes:
      - db_data:/var/lib/postgresql/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db_data:
